### ISSUE TITLE
KB Shortcuts

### ISSUE THREAD

**Issue by cassidyjames** [system76/pop-default-settings#13]
I've been documenting these and trying to wrangle them with any obvious improvements.

[WIP Google Doc](https://docs.google.com/document/d/1XryPXP2NA3_LC395sJV2pd9o1TUjyCQ8TXbmt0CG_1I/edit?usp=sharing)

**Comment by jackpot51** [comment]
I set the rest here: https://github.com/system76/pop-default-settings/commit/a1905c8851768683c4e48233316cd6d08f8b3057

**Comment by jackpot51** [comment]
One last thing though - we may want to consider leaving the Home shortcut, as it cannot have more than one shortcut.
