### ISSUE TITLE
Super+T keyboard shortcut is surprising

### ISSUE THREAD

**Issue by jbicha** [system76/pop-default-settings#18]
As a long time Ubuntu user, I was surprised that Ctrl+Alt+T didn't work to open a terminal.

As long as there is only one keyboard shortcut allowed for this action (see https://github.com/system76/pop-default-settings/issues/12), I recommend using Ctrl+Alt+T for backwards compatibility.

**Comment by jackpot51** [comment]
It may be possible to include both using custom shortcuts.

**Comment by cassidyjames** [comment]
Thanks for the feedback!

We set our keyboard shortcuts after a long dive into investigating GNOME and Ubuntu shortcuts, as well as some simpler ideals. We had a long discussion about how to handle long-time keyboard shortcuts that we changed for Pop!_OS, like the Ctrl + Alt + T, (and Ctrl + Alt + Up/Down) and came to the conclusion that including duplicate shortcuts discouraged users from learning the new, consistent ones for Pop!_OS. While this might be minorly painful for transitioning users (or those who switch between desktops), it's better for the long-term of Pop!_OS.

You are absolutely encouraged to set any muscle memory shortcuts in the Settings, though, if you find you can't live without them. :wink:

**Comment by jbicha** [comment]
Ok, I guess it is documented too:

http://pop.system76.com/docs/keyboard-shortcuts/
