### ISSUE TITLE
Hide pop-app-folders

### ISSUE THREAD

**Issue by jbicha** [system76/pop-default-settings#19]
`/etc/xdg/autostart/pop-app-folders.desktop`

is missing this line
`NoDisplay=true`

Adding that line will keep pop-app-folders from showing in Startup Applications. It's not something I think you want users to be easily disabling.

**Comment by jackpot51** [comment]
Thanks, I will add that.

**Comment by jackpot51** [comment]
Fixed here: https://github.com/system76/pop-default-settings/commit/7838e70a7d7b6124de7aafa7bfe74365274aa0dc

It will be in the repository soon.
