### ISSUE TITLE
Consider using dark theme for terminal

### ISSUE THREAD

**Issue by jackpot51** [system76/pop-default-settings#21]
This can be done using the gsetting override:
```
[org.gnome.Terminal.Legacy]
theme-variant = 'dark'
```

**Comment by WatchMkr** [comment]
Is this completed?

**Comment by jackpot51** [comment]
No, @WatchMkr is this something you are interested in?

**Comment by WatchMkr** [comment]
We're keeping it light and going to work on light terminal theme improvements.
