### ISSUE TITLE
Default Terminal Program Tilix.

### ISSUE THREAD

**Issue by kylerchin** [system76/pop-default-settings#6]
Can we get tilix in as our program? Many users have requested to use Tilix.

**Comment by jrock2004** [comment]
Is this not just tmux?

**Comment by kylerschin** [comment]
yes, but better and more customizable. @jrock2004.
What do you think @isantop

**Comment by ryanleesipes** [comment]
This discussion needs to happen on the [SubReddit forum](https://reddit.com/r/pop_os) - I think it's unlikely this will happen, unless there is some technical argument that can be made to Tilix's superiority to GNOME Terminal. As someone who would like to see this, I think we should try to get GNOME to adopt Tilix as the default terminal.

**Comment by jackpot51** [comment]
We are going to keep gnome-terminal as the default terminal program.
