### ISSUE TITLE
Utilities and Viewers organization in the app drawer

### ISSUE THREAD

**Issue by jackpot51** [system76/pop-default-settings#9]
This involves design work - deciding which icons are part of the folders, as well as work in this repository to set the values correctly.

**Comment by jackpot51** [comment]
I have already set up two folders, Utilities and Viewers, using what I think are good defaults. I will await further direction from @cassidyjames on what more to include.

See https://github.com/system76/pop-default-settings/commit/c0732c0cfe98cf39d0deb524bf92c8d38dec7c2c for more information

**Comment by jackpot51** [comment]
The implementation of this is harder than it seems. I had to pull it out here: https://github.com/system76/pop-default-settings/commit/ee54d69bf75891e74043f1aa59cf7ee3858a4c15

Folders cannot be created except by running commands as the user, which just happens to be done by `gnome-software` to create the Utilities and Sundry folders. The relevant code is here: https://github.com/GNOME/gnome-software/blob/master/src/gs-folders.c#L541

**Comment by jackpot51** [comment]
Fixed in https://github.com/system76/pop-default-settings/commit/f2ebdd78f6dd5e12263f4d9471b1fd694626b3fd

Building here: https://launchpad.net/~system76/+archive/ubuntu/pop-staging/+build/13376488

**Comment by WatchMkr** [comment]
This looks great! I use Disk Usage Analyzer a decent amount. I'd consider it a utility.

**Comment by jackpot51** [comment]
@cassidyjames @WatchMkr I have made some minor modifications, here is a proposed list:

# Folder-less

- Pop!_Shop
- Contacts
- Files
- Firefox
- Geary
- Calculator
- Calendar
- Settings
- Simple Scan
- Text Editor
- Terminal
- Weather

# Utilities

- Archive Manager
- Character Map
- Document Viewer
- Eddy
- Fonts
- Help
- Image Viewer
- Screenshot
- Videos

# System

- Disk Usage Analyzer
- Disks
- Input Method
- Language Support
- Passwords & Keys
- Power Statistics
- Software & Updates
- Startup Applications
- System Monitor

# Office

- LibreOffice
- LibreOffice Calc
- LibreOffice Draw
- LibreOffice Impress
- LibreOffice Math
- LibreOffice Writer

**Comment by jackpot51** [comment]
Also, if we will pre-install the NVIDIA drivers, maybe the X server settings should go in System?

**Comment by jackpot51** [comment]
This is now in pop-default-settings 1.2.5
